config/routes.rb
Airlines::Application.routes.draw do
  get "routes/new"
  root 'worlds#index'

  resources :worlds
  resources :airlines
  resources :routes
  resources :aircraft_configurations
  resources :aircraft_types
  resources :aircrafts

  get 'get_quote' => 'manufacturers#get_quote'

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  belongs_to      :airline
  belongs_to      :aircraft_type
  belongs_to      :aircraft_configuration
end

app/models/aircraft_configuration.rb
class AircraftConfiguration < ActiveRecord::Base

  belongs_to :aircraft_type
  belongs_to :aircraft
  belongs_to :airline

  validates   :aircraft_type, :first_seats, :business_seats, :economy_seats, presence: true
end

app/models/aircraft_type.rb
class AircraftType < ActiveRecord::Base
end

app/models/airline.rb
class Airline < ActiveRecord::Base
  belongs_to  :world
  has_many    :routes
  has_many    :flights
  has_many    :aircrafts
  has_many    :aircraft_configurations
  has_one     :bank_account

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many    :routes, as: :departure_airport
  has_many    :routes, as: :arrival_airport
  has_many    :outgoing_flights, class_name: 'Flight', foreign_key: :departure_airport_id
  has_many    :incoming_flights, class_name: 'Flight', foreign_key: :incoming_airport_id
end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  belongs_to        :airline
end

app/models/engine.rb
class Engine < ActiveRecord::Base
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  scope :outgoing, -> (departure_airport) { where('departure_airport_id = ?', departure_airport.id) }

  belongs_to      :airline
  belongs_to      :route
  belongs_to      :aircraft
  belongs_to      :arrival_airport, class_name: "Airport", foreign_key: :arrival_airport_id
  belongs_to      :departure_airport, class_name: "Airport", foreign_key: :departure_airport_id
end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  belongs_to :airline

  def base_passengers
    passengers = 0
    passengers = (departure_airport.daily_origin_pax + arrival_airport.daily_destination_pax)/100
    passengers = passengers + arrival_airport.outgoing_flights.count*1
    passengers = passengers + airline.flights.outgoing(arrival_airport).count*3
    passengers.floor
    # TODO: fix bug that reverse flights increase number of passengers.
  end

  def first_passengers
    (base_passengers*0.02).floor
  end

  def business_passengers
    (base_passengers*0.10).floor
  end

  def economy_passengers
    (base_passengers*0.88).floor
  end
end

app/models/world.rb
class World < ActiveRecord::Base
  has_many :airlines
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  def new
    @aircraft_type = AircraftType.find(params[:aircraft_type_id])
    @aircraft = current_airline.aircrafts.new(aircraft_type: @aircraft_type)
    @aircraft_configurations = current_airline.aircraft_configurations.where(aircraft_type: @aircraft_type).all
  end
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
  def show
    @airline = Airline.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action       :find_world

  def find_world
    @world = @world || World.first
  end

  def current_airline
    @current_airline = @current_airline || Airline.first
  end
  helper_method :current_airline
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def new
    @departure_airport = Airport.find(1)
    @arrival_airport = Airport.find(2)
    @route = Route.new(departure_airport: @departure_airport, arrival_airport: @arrival_airport, airline: Airline.first)
  end
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  def index
    @worlds = World.all
  end
end

app/helpers/aircraft_types_helper.rb
module AircraftTypesHelper
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/airlines/show.haml
.page-header
  .row
    .col-lg-12
      %h1= @airline.name

app/views/routes/new.haml
.page-header
  .row
    .col-lg-12
      %h1 New route
%script{ src: "https://maps.googleapis.com/maps/api/js?sensor=false" }
:javascript
  function initialize() {
    var mapOptions = {
      zoom: 5,
      center: new google.maps.LatLng(51.874699, -0.368333),
      mapTypeId: google.maps.MapTypeId.TERRAIN
    };

    /*var geocoder = new google.maps.Geocoder();
    var flightPlanCoordinates = [];
    var address = 'BHX';
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK)
      {
        flightPlanCoordinates.push(new google.maps.LatLng(results[0].geometry.location.latitude, results[0].geometry.longitude));
      }
    });
    var address = 'LTN';
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK)
        {
          flightPlanCoordinates.push(new google.maps.LatLng(results[0].geometry.location.latitude, results[0].geometry.longitude));
        }
      });
    */
    var map = new google.maps.Map(document.getElementById('map_canvas'),
        mapOptions);

    var flightPlanCoordinates = [
      new google.maps.LatLng(51.874699, -0.368333),
      new google.maps.LatLng(52.453899, -1.748030)
    ];

    var flightPath = new google.maps.Polyline({
      path: flightPlanCoordinates,
      geodesic: true,
      strokeColor: '#FF0000',
      strokeOpacity: 1.0,
      strokeWeight: 2
    });

    flightPath.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
.row
  .row-log-12
    = form_tag({},{ class: 'form-horizontal' }) do
      .form-group
        %label.col-sm-3.control-label{for: "inputEmail3"} Departure:
        .col-sm-9
          %select.form-control
            %option Birmginham
            %option London LTN
      .form-group
        %label.col-sm-3.control-label{for: "inputEmail3"} Arrival:
        .col-sm-9
          %select.form-control
            %option Birmginham
            %option London LTN
.row
  .col-lg-12
    %ul.nav.nav-tabs
      %li.dropdown
        %a{href: "#"} Market research
        %a{href: "#"} Competition
.row
  .col-md-4
    .panel.panel-default
      .panel-heading
        Departure airport
      .panel-body
        %dl.dl-horizontal
          %dt Name:
          %dd= @departure_airport.name
          %dt Code:
          %dd= @departure_airport.code
          %dt Country:
          %dd= @departure_airport.country

  .col-md-4
    #map_canvas{ style: 'width: 100%; height: 300px;' }
  .col-md-4
    %h4 Arrival airport
    %dl.dl-horizontal
      %dt Name:
      %dd= @arrival_airport.name
      %dt Code:
      %dd= @arrival_airport.code
      %dt Country:
      %dd= @arrival_airport.country
.row
  .col-md-4
    %h4 Passanger demand
    = column_chart [["First", @route.first_passengers],["First Seats",0],["Business", @route.business_passengers],["Business Seats",0],["Economy", @route.economy_passengers],["Economy Seats",0]], library: {}
  .col-md-4
    %h4 Revenue management
  .col-md-4
    %h4 Market share

app/views/worlds/_world.haml
%tr
  %td= world.id
  %td= link_to world.name, world_path(world)

app/views/worlds/index.haml
.page-header
  .row
    .col-lg-12
      %h1 Worlds
.row
  .col-lg-12
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th #
          %th Name
      %tbody
        = render @worlds if @worlds