config/routes.rb
Airlines::Application.routes.draw do
  get "routes/new"
  root 'worlds#index'

  resources :worlds
  resources :airlines
  resources :routes
  resources :aircraft_configurations
  resources :aircraft_types
  resources :aircrafts

  get 'get_quote' => 'manufacturers#get_quote'

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  belongs_to      :airline
  belongs_to      :aircraft_type
  belongs_to      :aircraft_configuration
end

app/models/aircraft_configuration.rb
class AircraftConfiguration < ActiveRecord::Base

  belongs_to :aircraft_type
  belongs_to :aircraft
  belongs_to :airline

  validates   :aircraft_type, :first_seats, :business_seats, :economy_seats, presence: true
end

app/models/aircraft_type.rb
class AircraftType < ActiveRecord::Base
end

app/models/airline.rb
class Airline < ActiveRecord::Base
  belongs_to  :world
  has_many    :routes
  has_many    :flights
  has_many    :aircrafts
  has_many    :aircraft_configurations
  has_one     :bank_account

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many    :routes, as: :departure_airport
  has_many    :routes, as: :arrival_airport
  has_many    :outgoing_flights, class_name: 'Flight', foreign_key: :departure_airport_id
  has_many    :incoming_flights, class_name: 'Flight', foreign_key: :incoming_airport_id
end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  belongs_to        :airline
end

app/models/engine.rb
class Engine < ActiveRecord::Base
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  scope :outgoing, -> (departure_airport) { where('departure_airport_id = ?', departure_airport.id) }

  belongs_to      :airline
  belongs_to      :route
  belongs_to      :aircraft
  belongs_to      :arrival_airport, class_name: "Airport", foreign_key: :arrival_airport_id
  belongs_to      :departure_airport, class_name: "Airport", foreign_key: :departure_airport_id
end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  belongs_to :airline

  def base_passengers
    passengers = 0
    passengers = (departure_airport.daily_origin_pax + arrival_airport.daily_destination_pax)/100
    passengers = passengers + arrival_airport.outgoing_flights.count*1
    passengers = passengers + airline.flights.outgoing(arrival_airport).count*3
    passengers.floor
    # TODO: fix bug that reverse flights increase number of passengers.
  end

  def first_passengers
    (base_passengers*0.02).floor
  end

  def business_passengers
    (base_passengers*0.10).floor
  end

  def economy_passengers
    (base_passengers*0.88).floor
  end
end

app/models/world.rb
class World < ActiveRecord::Base
  has_many :airlines
end

app/controllers/aircraft_configurations_controller.rb
class AircraftConfigurationsController < ApplicationController
  def index
    @aircraft_configurations = current_airline.aircraft_configurations
  end

  def new
    aircraft_type = AircraftType.find(params[:aircraft_type_id])
    @aircraft_configuration = current_airline.aircraft_configurations.new(aircraft_type: aircraft_type)
  end

  def create
    @aircraft_configuration = current_airline.aircraft_configurations.new(aircraft_configuration_params)
    if @aircraft_configuration.save
      redirect_to aircraft_configurations_path, flash: { success: "Aircraft configuration saved." }
    else
      render 'new'
    end
  end

  private

  def aircraft_configuration_params
    params.require(:aircraft_configuration).permit(:aircraft_type_id, :name, :first_seats, :business_seats, :economy_seats)
  end
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  def new
    @aircraft_type = AircraftType.find(params[:aircraft_type_id])
    @aircraft = current_airline.aircrafts.new(aircraft_type: @aircraft_type)
    @aircraft_configurations = current_airline.aircraft_configurations.where(aircraft_type: @aircraft_type).all
  end
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
  def show
    @airline = Airline.find(params[:id])
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def new
    @departure_airport = Airport.find(1)
    @arrival_airport = Airport.find(2)
    @route = Route.new(departure_airport: @departure_airport, arrival_airport: @arrival_airport, airline: Airline.first)
  end
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  def index
    @worlds = World.all
  end
end

app/helpers/aircraft_configurations_helper.rb
module AircraftConfigurationsHelper
end

app/helpers/aircraft_types_helper.rb
module AircraftTypesHelper
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/aircraft_configurations/index.haml
.page-header
  .row
    .col-lg-12
      %h1 Aircraft Configurations
.row
  .col-lg-4
    %h4 Make new configuration for:
  .col-lg-8
    = form_tag(new_aircraft_configuration_path, method: "get", class: 'form-inline') do
      .form-group
        = label_tag(:aircraft_type_id, 'Aircraft Type: ')
        = select_tag(:aircraft_type_id, options_for_select(AircraftType.all.map{ |type| [type.name, type.id] }), class: 'form-control' )
        = submit_tag("Go", class: 'btn btn-primary')
.row
  .col-lg-12
    %table.table.table-striped.table-hover.tablesorter
      %thead
        %tr
          %th #
          %th Name
          %th Aircraft
          %th first seats
          %th business seats
          %th economy seats
          %th
      %tbody
        - @aircraft_configurations.each_with_index do |config,i|
          %tr
            %td= i
            %td= config.name
            %td= config.aircraft_type.name
            %td= config.first_seats
            %td= config.business_seats
            %td= config.economy_seats
            %td
              = link_to 'Edit', '#', class: 'btn btn-primary btn-xs'
:javascript
  $(".table").tablesorter();

app/views/aircraft_configurations/new.haml
.row
  .col-lg-12
    .page-header
      %h1 New aircraft configuration
.row
  .col-sm-12
    .row
      = form_for @aircraft_configuration, builder: StandardBuilder, html: { class: "form-horizontal" } do |f|
        = f.error_messages
        .form-group
          = f.text_field :aircraft_type_id, value: @aircraft_configuration.aircraft_type_id, type: 'hidden'
          = f.label :name, class: 'col-sm-2 control-label'
          .col-sm-4= f.text_field :name, class: 'form-control'
          .col-sm-2
            %input#first-seats.control-label.form-control{ type: 'number' }
        .form-group
          = f.label :first_seats, class: 'col-sm-2 control-label'
          .col-sm-4= f.text_field :first_seats, class: 'form-control', type: 'number'
          .col-sm-2
            %input#business-seats.control-label.form-control{ type: 'number' }
        .form-group
          = f.label :business_seats, class: 'col-sm-2 control-label'
          .col-sm-4= f.text_field :business_seats, class: 'form-control', type: 'number'
        .form-group
          = f.label :economy_seats, class: 'col-sm-2 control-label'
          .col-sm-4= f.text_field :economy_seats, class: 'form-control', type: 'number'
        .form-group
          = f.submit 'Create configuration', class: 'btn btn-success'