config/routes.rb
Airlines::Application.routes.draw do
  get "routes/new"
  root 'worlds#index'

  resources :worlds
  resources :airlines
  resources :routes
  resources :aircraft_configurations
  resources :aircraft_types
  resources :aircrafts

  get 'get_quote' => 'manufacturers#get_quote'

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  belongs_to      :airline
  belongs_to      :aircraft_type
  belongs_to      :aircraft_configuration
end

app/models/aircraft_configuration.rb
class AircraftConfiguration < ActiveRecord::Base

  belongs_to :aircraft_type
  belongs_to :aircraft
  belongs_to :airline

  validates   :aircraft_type, :first_seats, :business_seats, :economy_seats, presence: true
end

app/models/aircraft_type.rb
class AircraftType < ActiveRecord::Base
end

app/models/airline.rb
class Airline < ActiveRecord::Base
  belongs_to  :world
  has_many    :routes
  has_many    :flights
  has_many    :aircrafts
  has_many    :aircraft_configurations
  has_one     :bank_account

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many    :routes, as: :departure_airport
  has_many    :routes, as: :arrival_airport
  has_many    :outgoing_flights, class_name: 'Flight', foreign_key: :departure_airport_id
  has_many    :incoming_flights, class_name: 'Flight', foreign_key: :incoming_airport_id
end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  belongs_to        :airline
end

app/models/engine.rb
class Engine < ActiveRecord::Base
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  scope :outgoing, -> (departure_airport) { where('departure_airport_id = ?', departure_airport.id) }

  belongs_to      :airline
  belongs_to      :route
  belongs_to      :aircraft
  belongs_to      :arrival_airport, class_name: "Airport", foreign_key: :arrival_airport_id
  belongs_to      :departure_airport, class_name: "Airport", foreign_key: :departure_airport_id
end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  belongs_to :airline

  def base_passengers
    passengers = 0
    passengers = (departure_airport.daily_origin_pax + arrival_airport.daily_destination_pax)/100
    passengers = passengers + arrival_airport.outgoing_flights.count*1
    passengers = passengers + airline.flights.outgoing(arrival_airport).count*3
    passengers.floor
    # TODO: fix bug that reverse flights increase number of passengers.
  end

  def first_passengers
    (base_passengers*0.02).floor
  end

  def business_passengers
    (base_passengers*0.10).floor
  end

  def economy_passengers
    (base_passengers*0.88).floor
  end
end

app/models/world.rb
class World < ActiveRecord::Base
  has_many :airlines
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
  def show
    @airline = Airline.find(params[:id])
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def new
    @departure_airport = Airport.find(1)
    @arrival_airport = Airport.find(2)
    @route = Route.new(departure_airport: @departure_airport, arrival_airport: @arrival_airport, airline: Airline.first)
  end
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  def index
    @worlds = World.all
  end
end

app/helpers/aircraft_types_helper.rb
module AircraftTypesHelper
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Airlines
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = csrf_meta_tags
  %body{ class: "#{params[:controller]}-#{params[:action]}" }
    .navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %a.navbar-brand{href: "../"} Bootswatch
          %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", type: "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #navbar-main.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li.dropdown
              %a#themes.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Themes
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "themes"}
                %li
                  %a{href: "../default/"} Default
                %li.divider
                %li
                  %a{href: "../amelia/"} Amelia
            %li
              %a{href: "../help/"} Help
            %li
              %a{href: "http://news.bootswatch.com"} Blog
            %li.dropdown
              %a#download.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Aircraft
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "download"}
                %li= link_to "Configurations", aircraft_configurations_path
                %li= link_to "Aircraftlist", aircraft_types_path
                %li
                  %a{href: "./bootstrap.css"} bootstrap.css
                %li.divider
                %li
                  %a{href: "./variables.less"} variables.less
                %li
                  %a{href: "./bootswatch.less"} bootswatch.less
          %p.navbar-text= @world.time.strftime("%e. %b, %Y - %H:%M")
          %p.navbar-text= number_to_currency current_airline.bank_account.balance
          %ul.nav.navbar-nav.navbar-right
  .container
    = yield